### ISSUE TITLE
Sometimes API doesn't respond

### ISSUE THREAD

**Issue by tmushayahama** [geneontology/api-gorest#1]
Sometimes the api doesn't give back (23% of the time). But there is CORS so I cannot tell you the actual error. This is an example of https://api.geneontology.cloud/models/pmid/ . Not only pmid but others too.

![image](https://user-images.githubusercontent.com/2273929/130830350-3dcc2bd3-37ee-4a12-8ed5-5b5753052f23.png)

Also this might be a good exercise to check how this api works while Laurent is here
tagging @dustine32 @sierra-moxon @lpalbou

**Comment by lpalbou** [comment]
As discussed, this is a CORS issue linked to you accessing from localhost. It happens from time to time but it doesn't happens once deployed (feel free to test online on the gocam website). The API itself is fail-proof, 100% always accessible but it does forward/proxy query to the SPARQL endpoint, which may fail or timeout.

**Comment by tmushayahama** [comment]
Aghh @lpalbou I just discovered it is not about the localhost but the upstream sparql. I was calling wrong API.

instead of https://s3.amazonaws.com/geneontology-public/gocam/gocam-gps.json  I was calling 
https://api.geneontology.cloud/models/gp/ . The latter has internal error message but returned as CORS instead. In the **future** any way to get the actual error message.
 In the meantime no worries will use the TEMP json api

**Comment by lpalbou** [comment]
Well, probably because the route you are trying to access doesn't exist without parameters ? ;)

If you look at the swagger (accessible from http://geneontology.org/go-cam , right panel REST endpoint), you will see that you need to indicate a GO-CAM id: [swagger doc](https://app.swaggerhub.com/apis-docs/geneontology/gosparql/2.2#/GO%20Causal%20Activity%20Models/get_models_gp)

Example: [https://api.geneontology.cloud/models/gp?gocams=59a6110e00000067](https://api.geneontology.cloud/models/gp?gocams=59a6110e00000067)

If that was your issue, then I think we are good and can close that ticket :)

**Comment by kltm** [comment]
Talking to @tmushayahama @dustine32 , this seems to be okay now.
